from .bank_accounts import BankAccounts
from .cities import Cities
from .companies import Companies
from .employee import Employee
from .person import Person
from .providers import Providers
from .provinces import Provinces
from .customer import Customer
from .vehicles import Vehicles
from .vehicle_owner import VehicleOwner
from .budgets import Budget
from .repair import Repair
